// svelte-demo/src/Main.svelte
<script>
import { getAuth } from './context/AuthContext/Provider.svelte'

import Home from './Home.svelte'
import Button from './components/Button.svelte'

let { status, login, logout } = getAuth()

</script>

{#if $status === 'unauth'}
  <div>
    <header>
      <Button on:click={login}>Log-in</Button>
    </header>
    Unauthenticated
  </div>
{:else if $status === 'pending'}
  <div>
    <header>
      pending ...
    </header>
    Authenticating...
  </div>
{:else if $status === 'auth'}
  <div>
    <header>
      <Button on:click={logout}>Log-out</Button>
    </header>
    <Home />
  </div>
{:else}    <!-- error state -->
  <div>
    Error while login <Button on:click={login}>Try again</Button>
  </div>
{/if}

// react-demo/src/Main.js
import React from 'react'
import { useAuth } from './context/AuthContext'

import { Home } from './Home'
import { Button } from './components/Button'

export const Main = () => {
  const auth = useAuth()
  return (
    auth.status === 'unauth' ? (
      <div>
        <header>
          <Button onClick={auth.login}>Log-in</Button>
        </header>
        Unauthenticated
      </div>
    ) : auth.status === 'pending' ? (
      <div>
        <header>
          pending ...
        </header>
        Authenticating...
      </div>
    ) : auth.status === 'auth' ? (
      <div>
        <header>
          <Button onClick={auth.logout}>Log-out</Button>
        </header>
        <Home />
      </div>
    ) : ( // error state
      <div>
        Error while login <Button onClick={auth.login}>Try again</Button>
      </div>
    )
  )
}
