// svelte-demo/src/components/Button.svelte

<button
    {...$$props}
    use:forwardEvents
    className={'button ' + ($$props.className || '')}
>
    <slot />
</button>

<script>
import { current_component } from 'svelte/internal'
import { forwardEventsBuilder } from '../utils/forwardEvents'

$: forwardEvents = forwardEventsBuilder(current_component)

</script>

<style>

button {
    background: none;
    background-color: #ff3e00;
    border-radius: 5px;
    padding: 10px 5px;
    color: white;
    border: none;
}

</style>

// react-demo/src/components/Button.js
import React from 'react'

export const Button = props => (
    <button
        {...props}
        className={'button ' + (props.className || '')}
        style={style}
    />
)

const style = {
    background: 'none',
    backgroundColor: '#40b3ff',
    borderRadius: '5px',
    padding: '10px 5px',
    border: 'none',
    color: 'white',
}
